### PR TITLE
Let's try this!

### PR DESCRIPTION
**Pull request by Hazuki-san**
I tested on my server and pp overwriting is working now ;p

### CODE REVIEW

**Comment by KotRikD** [comment]
Why i need that?

**Comment by Hazuki-san** [comment]
for PP overwriting, or I understand something wrong...?

**Comment by KotRikD** [comment]
i fix PP overwriting in last versions ;D

**Comment by KotRikD** [comment]
Just check commits from
16th and 17th October

**Comment by Hazuki-san** [comment]
Oh, I thought it is score overwriting instead of PP.
have you test that yet?

**Comment by KotRikD** [comment]
Yeah ofc, it on master branch and I use that branch for server)

**Pull request closed without merging**
